services:
  mysql:
    image: mysql:8.0
    container_name: invoice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: invoice_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  invoice-app:
    build:
      context: ./Invoice
      dockerfile: Dockerfile
    container_name: invoice-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/invoice_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build:
      context: Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:4000"
    depends_on:
      - invoice-app
    restart: unless-stopped

volumes:
  mysql-data:
